name: project_e
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  cloud_firestore:
  firebase_auth: ^0.6.6
  google_sign_in: ^3.2.4
  firebase_storage: ^1.0.4
  shared_preferences: ^0.4.3
  image_picker: ^0.4.10
  cached_network_image: ^0.5.1 
  intl: ^0.15.7
  url_launcher: ^4.0.3
  image_cropper: ^0.0.9
  uuid: ^1.0.3
  flutter_staggered_grid_view: "^0.2.6" 
  fluttertoast: ^2.2.6
  firebase_messaging: ^2.1.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/asset_1.png
    - assets/2.0x/asset_1.png
    - assets/3.0x/asset_1.png
    - assets/asset_2.png
    - assets/2.0x/asset_2.png
    - assets/3.0x/asset_2.png
    - assets/asset_3.png
    - assets/2.0x/asset_3.png
    - assets/3.0x/asset_3.png
    - assets/asset_4.png
    - assets/2.0x/asset_4.png
    - assets/3.0x/asset_4.png
    - assets/asset_5.png
    - assets/2.0x/asset_5.png
    - assets/3.0x/asset_5.png
    - assets/asset_6.png
    - assets/2.0x/asset_6.png
    - assets/3.0x/asset_6.png
    - assets/asset_7.png
    - assets/2.0x/asset_7.png
    - assets/3.0x/asset_7.png
    - assets/asset_8.png
    - assets/2.0x/asset_8.png
    - assets/3.0x/asset_8.png
    - assets/asset_9.png
    - assets/2.0x/asset_9.png
    - assets/3.0x/asset_9.png
    - assets/asset_10.png
    - assets/2.0x/asset_10.png
    - assets/3.0x/asset_10.png
    - assets/google_sign_in.png
    - assets/2.0x/google_sign_in.png
    - assets/3.0x/google_sign_in.png
    - assets/e_club.png
    - assets/2.0x/e_club.png
    - assets/3.0x/e_club.png
    - assets/e_club_1.png
    - assets/2.0x/e_club_1.png
    - assets/3.0x/e_club_1.png
    - assets/user_1.png
    - assets/2.0x/user_1.png
    - assets/3.0x/user_1.png
    - assets/user_2.png
    - assets/2.0x/user_2.png
    - assets/3.0x/user_2.png
    - assets/instagram.png
    - assets/2.0x/instagram.png
    - assets/3.0x/instagram.png
    - assets/facebook.png
    - assets/2.0x/facebook.png
    - assets/3.0x/facebook.png
    - assets/linkedin.png
    - assets/2.0x/linkedin.png
    - assets/3.0x/linkedin.png
    - assets/placeholder.png
    - assets/2.0x/placeholder.png
    - assets/3.0x/placeholder.png
    - assets/placeholder2.png
    - assets/2.0x/placeholder2.png
    - assets/3.0x/placeholder2.png
    - assets/google2.png
    - assets/2.0x/google2.png
    - assets/3.0x/google2.png
    - assets/screen1.png
    - assets/2.0x/screen1.png
    - assets/3.0x/screen1.png
    - assets/screen2.png
    - assets/2.0x/screen2.png
    - assets/3.0x/screen2.png
    - assets/screen3.png
    - assets/2.0x/screen3.png
    - assets/3.0x/screen3.png
    - assets/screen4.png
    - assets/2.0x/screen4.png
    - assets/3.0x/screen4.png
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/Rubik-Regular.ttf
        - asset: assets/Rubik-Medium.ttf
        - asset: assets/Rubik-Bold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
